### PR TITLE
fix build so works with pip install

### PR DESCRIPTION
**Pull request by robnagler**
When doing a pip install without this change, pip install fails with:
```txt
  CMake Error: The current CMakeCache.txt directory /var/tmp/radia-run-356-15095/pip-req-build-Ik7Sb3/third_party/build/CMakeCache.txt is different than the directory /home/vagrant/src/radiasoft/codes/pymesh-20190226.013946/PyMesh/third_party/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
  CMake Error: The source "/var/tmp/radia-run-356-15095/pip-req-build-Ik7Sb3/third_party/CMakeLists.txt" does not match the source "/home/vagrant/src/radiasoft/codes/pymesh-20190226.013946/PyMesh/third_party/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory
```
Took the opportunity to share the build code between
the third_party and pymesh builds, which also allows
pymesh build to use NUM_CORES feature.
Removed all references to root_dir.
Removed unnecessary semicolons

### CODE REVIEW

**Comment by AAcquier** [comment]
Tell me then why do I get this error when using pip install pymesh2:

> Command "/home/alex/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-1V9Y5f/pymesh2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-bxrP7U/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-1V9Y5f/pymesh2/

**Comment by qnzhou** [comment]
@AAcquier please download the `.whl` file on the [release page](https://github.com/PyMesh/PyMesh/releases), and do `pip instsall <filename>.whl`.  The `pymesh2` package on PyPI is out of date.

**Comment by AAcquier** [comment]
I have done that already and I am getting exactly the same error that in #141

**Comment by AAcquier** [comment]
I have done what you told me, pymesh2-0.2.1-cp27-cp27mu-linux_x86_64.whl gave me that same error described in #141  but pymesh2-0.2.0-cp27-cp27mu-linux_x86_64.whl seems to work very well

**Comment by robnagler** [comment]
@AAcquier does this work?

pip install git+git://github.com/PyMesh/PyMesh.git

**Comment by AAcquier** [comment]
Tried that and that what gave me the error from #141 the first time, only by using the 0.2.0 wheel release did I manage to get it working. It looks like the Mesh.py file is saying it is missing a PyMesh.py (as far as I understand it) but by any mean it looked like it was installed properly as it was clearly showing in the site_packages folder and all.

**Pull request merged**
